@startuml
!include style.iuml
left to right direction
hide methods
hide fields

class ArtistPage <<Path>>
class CustomerPage <<Path>>
class ItemPage <<Path>>
class PublisherPage <<Path>>
class PurchaseOrderPage <<Path>>

@enduml
