@startuml
!include style.iuml


class Artist <<POJO>>{
  - id: Long
  - name: String
  - bio: String
  - createdDate: Instant
  + getId(): Long
  + setId(Long): void
  + getName(): String
  + setName(String): void
  + getBio(): String
  + setBio(String): void
  + getCreatedDate(): Instant
  + setCreatedDate(Instant): void
}
@enduml
