@startuml
!include style.iuml
left to right direction

class ArtistResource <<Path>>
class CustomerResource <<Path>>
class ItemResource <<Path>>
class PublisherResource <<Path>>
class PurchaseOrderResource <<Path>>

ArtistResource-[hidden]-CustomerResource
CustomerResource-[hidden]-ItemResource
PublisherResource-[hidden]-PurchaseOrderResource

@enduml
